[versions]
lombok = "1.18.38"
spigot-api = "1.16.5-R0.1-SNAPSHOT"
paper-api = "1.16.5-R0.1-SNAPSHOT"
bungeecord-api = "1.20-R0.1-SNAPSHOT"
dream-utilties = "1.5.3"
okaeri-placeholders = "5.1.1"
okaeri-configs = "5.0.8"
adventure-minimessage = "4.21.0"
adventure-serializer = "4.21.0"
adventure-platform-bukkit = "4.3.4"
adventure-platform-bungee = "4.3.4"
xseries = "13.2.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot-api" }
paper-api = { module = "com.destroystokyo.paper:paper-api", version.ref = "paper-api" }
bungeecord-api = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord-api" }
dream-utilties = { module = "cc.dreamcode:utilities", version.ref = "dream-utilties" }
dream-utilties-bukkit = { module = "cc.dreamcode:utilities-bukkit", version.ref = "dream-utilties" }
dream-utilties-bukkit-adventure = { module = "cc.dreamcode:utilities-bukkit-adventure", version.ref = "dream-utilties" }
dream-utilties-bungee = { module = "cc.dreamcode:utilities-bungee", version.ref = "dream-utilties" }
dream-utilties-bungee-adventure = { module = "cc.dreamcode:utilities-bungee-adventure", version.ref = "dream-utilties" }
okaeri-placeholders = { module = "eu.okaeri:okaeri-placeholders-core", version.ref = "okaeri-placeholders" }
okaeri-configs = { module = "eu.okaeri:okaeri-configs-core", version.ref = "okaeri-configs" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-minimessage" }
adventure-serializer = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure-serializer" }
adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform-bukkit" }
adventure-platform-bungee = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventure-platform-bungee" }
xseries = { module = "com.github.cryptomorin:XSeries", version.ref = "xseries" }